name: NMinimap
version: '1.0.4-quickfix-1'
main: su.nezushin.nminimap.NMinimap
api-version: '1.21'

authors:
  - NezuShin
  - DartCat25

commands:
  minimap:
    aliases: [mm]

softdepend:
  - packetevents
  - PassengerAPI
  - AnvilORM
  - PlaceholderAPI


folia-supported: true

libraries:
  - net.kyori:adventure-text-minimessage:4.23.0
  - net.kyori:adventure-platform-bukkit:4.4.0
  - com.tchristofferson:ConfigUpdater:2.2
  - de.clickism:modrinth-update-checker:1.0